### ISSUE TITLE
파싱 부 실행부 합치기

### ISSUE THREAD

**Issue by brixxt27** [Arkingco/42_cub3d#26]
# ISSUE
 * Detail: 파싱 부 실행부 합치기
 
# TODO

### 파싱
- [x] 플레이어 위치 찾아서 맵핑 해주기 파싱 시 캐릭터 위치를 배열에서 읽고 map_info 로 가지고 있기
- [x] ceiling, floor RGB 값 파싱 후, 매핑하기
1. mlx에서 천장과 바닥의 색과 투명도를 표현하기 위해서는 4byte의 메모리가 필요하다.
2. 0xFF FF FF FF 가장 왼쪽에 있는 바이트 순서대로 투명도, red, green, blue 이다.

- [x] 맵 크기제한 구현
- [x] start position의 정보는 이미 가지고 있으니 스폰 위치를 의미하는 문자를 0으로 변경하여 맵을 가지고 있기
### 게임
- [x] 미니맵 배경 색 투명하게 바꾸기 => 미니맵을 검은색으로 칠하고 투명도를 줬다.
- [x] 캐릭터 스폰 시 문자에 따른 바라 보는 위치 구현

## <선택>
- [x] 미니맵 레이 벽 사이에 삐져 나오는거 처리하기
- [ ] 동서남북 텍스처 다른 이미지로 바꾸기
- [x] mlx 라이브러리 예외처리
